services:
  - type: web
    name: email-countdown
    env: node
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y \
        libcairo2-dev \
        libpango1.0-dev \
        libjpeg-dev \
        libgif-dev \
        librsvg2-dev
      npm install
    startCommand: npm start
